export interface ComponentConfig {
  id: string;
  title: string;
  description: string;
  category: string;
  // Componentes dinámicos
  frontComponent?: () => Promise<any>; // Función de importación para front-end
  backComponent?: () => Promise<any>;  // Función de importación para back-office
  previewComponent?: () => Promise<any>;  // Función de importación para preview
  // Flags de visibilidad por página
  showInHome: boolean;
  showInAbout: boolean;
  // Configuración adicional
  props?: Record<string, any>; // Props específicas para el componente
}

export const availableComponents: ComponentConfig[] = [
  {
    id: "Destacados",
    title: "Destacados",
    description: "Destacados de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Destacados/Destacado01'),
    backComponent: () => import('@/components/PIXELUP/Destacados/Destacado01BO'),
    previewComponent: () => import('@/components/PIXELUP/Destacados/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "marqueeTOP",
    title: "Marquee",
    description: "Banner de texto deslizante en la parte superior",
    category: "Contenido",
    frontComponent: () => import('@/components/conMantenedor/MarqueeTOP'),
    backComponent: () => import('@/components/PIXELUP/Marquee/MarqueeTop/BackOffice/MarqueeBO'),
    previewComponent: () => import('@/components/PIXELUP/Marquee/MarqueeTop/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "frase01",
    title: "Frase 01",
    description: "Frase de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Frases/Frase01/Frase01'),
    backComponent: () => import('@/components/PIXELUP/Frases/BackOffice/FrasesBO'),
    previewComponent: () => import('@/components/PIXELUP/Frases/Frase01/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "hero01",
    title: "Hero 01",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero01/Hero01'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero01/Hero01BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero01/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero02",
    title: "Hero 02",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero02/Hero02'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero02/Hero02BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero02/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero03",
    title: "Hero 03",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero03/Hero03'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero03/Hero03BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero03/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero04",
    title: "Hero 04",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero04/Hero04'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero04/Hero04BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero04/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero05",
    title: "Hero 05",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero05/Hero05'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero05/Hero05BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero05/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero06",
    title: "Hero 06",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero06/Hero06'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero06/Hero06BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero06/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero07",
    title: "Hero 07",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero07/Hero07'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero07/Hero07BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero07/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero08",
    title: "Hero 08",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero08/Hero08'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero08/Hero08BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero08/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero09",
    title: "Hero 09",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero09/Hero09'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero09/Hero09BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero09/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero10",
    title: "Hero 10",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero10/Hero10'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero10/Hero10BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero10/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero11",
    title: "Hero 11",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero11/Hero11'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero11/Hero11BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero11/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero12",
    title: "Hero 12",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero12/Hero12'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero12/Hero12BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero12/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero13",
    title: "Hero 13",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero13/Hero13'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero13/Hero13BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero13/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero14",
    title: "Hero 14",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero14/Hero14'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero14/Hero14BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero14/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero15",
    title: "Hero 15",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero15/Hero15'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero15/Hero15BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero15/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero16",
    title: "Hero 16",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero16/Hero16'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero16/Hero16BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero16/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero17",
    title: "Hero 17",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero17/Hero17'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero17/Hero17BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero17/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero18",
    title: "Hero 18",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero18/Hero18'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero18/Hero18BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero18/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "hero19",
    title: "Hero 19",
    description: "Hero de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Hero/Hero19/Hero19'),
    backComponent: () => import('@/components/PIXELUP/Hero/Hero19/Hero19BO'),
    previewComponent: () => import('@/components/PIXELUP/Hero/Hero19/Preview'),
    showInHome: true,
    showInAbout: true,
  },

  {
    id: "materiales",
    title: "Materiales",
    description: "Materiales de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/Materiales/Materiales'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/Materiales/MaterialesBO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/Materiales/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "materiales02",
    title: "Materiales 02",
    description: "Materiales de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/Materiales02/Materiales02'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/Materiales02/Materiales02BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/Materiales02/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto01",
    title: "Sin Foto 01",
    description: "Sin Foto 01 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto01/SinFoto01'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto01/SinFoto01BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto01/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto02",
    title: "Sin Foto 02",
    description: "Sin Foto 02 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto02/SinFoto02'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto02/SinFoto02BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto02/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto03",
    title: "Sin Foto 03",
    description: "Sin Foto 03 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto03/SinFoto03'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto03/SinFoto03BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto03/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto04",
    title: "Sin Foto 04",
    description: "Sin Foto 04 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto04/SinFoto04'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto04/SinFoto04BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto04/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto05",
    title: "Sin Foto 05",
    description: "Sin Foto 05 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto05/SinFoto05'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto05/SinFoto05BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto05/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto06",
    title: "Sin Foto 06",
    description: "Sin Foto 06 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto06/SinFoto06'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto06/SinFoto06BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto06/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto07",
    title: "Sin Foto 07",
    description: "Sin Foto 07 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto07/SinFoto07'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto07/SinFoto07BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto07/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto08",
    title: "Sin Foto 08",
    description: "Sin Foto 08 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto08/SinFoto08'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto08/SinFotoBO08'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto08/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto09",
    title: "Sin Foto 09",
    description: "Sin Foto 09 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto09/SinFoto09'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto09/SinFoto09BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto09/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto10",
    title: "Sin Foto 10",
    description: "Sin Foto 10 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto10/SinFoto10'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto10/SinFoto10BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto10/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto11",
    title: "Sin Foto 11",
    description: "Sin Foto 11 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto11/SinFoto11'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto11/SinFoto11BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto11/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto12",
    title: "Sin Foto 12",
    description: "Sin Foto 12 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto12/SinFoto12'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto12/SinFoto12BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto12/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto13",
    title: "Sin Foto 13",
    description: "Sin Foto 13 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto13/SinFoto13'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto13/SinFoto13BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto13/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "sinFoto14",
    title: "Sin Foto 14",
    description: "Sin Foto 14 de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto14/SinFoto14'),
    backComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto14/SinFoto14BO'),
    previewComponent: () => import('@/components/PIXELUP/SinFoto/SinFoto14/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "servicios01",
    title: "Servicios 01",
    description: "Servicios de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Servicios/Servicios01/Servicios01'),
    backComponent: () => import('@/components/PIXELUP/Servicios/Servicios01/Servicios01BO'),
    previewComponent: () => import('@/components/PIXELUP/Servicios/Servicios01/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "servicios02",
    title: "Servicios 02",
    description: "Servicios de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Servicios/Servicios02/Servicios02'),
    backComponent: () => import('@/components/PIXELUP/Servicios/Servicios02/Servicios02BO'),
    previewComponent: () => import('@/components/PIXELUP/Servicios/Servicios02/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "servicios03",
    title: "Servicios 03",
    description: "Servicios de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Servicios/Servicios03/Servicios03'),
    backComponent: () => import('@/components/PIXELUP/Servicios/Servicios03/Servicios03BO'),
    previewComponent: () => import('@/components/PIXELUP/Servicios/Servicios03/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "servicios04",
    title: "Servicios 04",
    description: "Servicios de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Servicios/Servicios04/Servicios04'),
    backComponent: () => import('@/components/PIXELUP/Servicios/Servicios04/Servicios04BO'),
    previewComponent: () => import('@/components/PIXELUP/Servicios/Servicios04/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "nosotros01",
    title: "Nosotros 01",
    description: "Nosotros de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Nosotros/Nosotros01/Nosotros01'),
    backComponent: () => import('@/components/PIXELUP/Nosotros/Nosotros01/Nosotros01BO'),
    previewComponent: () => import('@/components/PIXELUP/Nosotros/Nosotros01/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "parallax",
    title: "Parallax",
    description: "Parallax de la página",
    category: "Banners",
    frontComponent: () => import('@/components/PIXELUP/Parallax/Parallax'),
    backComponent: () => import('@/components/PIXELUP/Parallax/ParallaxBO'),
    previewComponent: () => import('@/components/PIXELUP/Parallax/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "bannerPrincipal01",
    title: "Banner Principal 01",
    description: "Banner principal de la página",
    category: "Banners",
    frontComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal01/BannerPrincipal01'),
    backComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal01/BannerPrincipal01BO'),
    previewComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal01/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "bannerPrincipal02",
    title: "Banner Principal 02",
    description: "Banner principal de la página",
    category: "Banners",
    frontComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal02/BannerPrincipal02'),
    backComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal02/BannerPrincipal02BO'),
    previewComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal02/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "bannerPrincipal03",
    title: "Banner Principal 03",
    description: "Banner principal de la página",
    category: "Banners",
    frontComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal03/BannerPrincipal03'),
    backComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal03/BannerPrincipal03BO'),
    previewComponent: () => import('@/components/PIXELUP/BannerPrincipal/BannerPrincipal03/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "galeria01",
    title: "Galeria 01",
    description: "Galeria de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Galeria/Galeria01/Galeria01'),
    backComponent: () => import('@/components/PIXELUP/Galeria/Galeria01/Galeria01BO'),
    previewComponent: () => import('@/components/PIXELUP/Galeria/Galeria01/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "galeria02",
    title: "Galeria 02",
    description: "Galeria de la página",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/Galeria/Galeria02/Galeria02'),
    backComponent: () => import('@/components/PIXELUP/Galeria/Galeria02/Galeria02BO'),
    previewComponent: () => import('@/components/PIXELUP/Galeria/Galeria02/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "logoscarrusel",
    title: "Logos Carrusel",
    description: "Logos Carrusel de la página",
    category: "Marcas",
    frontComponent: () => import('@/components/PIXELUP/Marcas/LogosCarrusel/LogosCarrusel'),
    backComponent: () => import('@/components/PIXELUP/Marcas/LogosCarrusel/LogosCarruselBO'),
    previewComponent: () => import('@/components/PIXELUP/Marcas/LogosCarrusel/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "logosfijos",
    title: "Logos Fijos",
    description: "Logos Fijos de la página",
    category: "Marcas",
    frontComponent: () => import('@/components/PIXELUP/Marcas/LogosFijos/LogosFijos'),
    backComponent: () => import('@/components/PIXELUP/Marcas/LogosFijos/LogosFijosBO'),
    previewComponent: () => import('@/components/PIXELUP/Marcas/LogosFijos/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "logosdinamicos",
    title: "Logos Dinámicos",
    description: "Logos Dinámicos de la página",
    category: "Marcas",
    frontComponent: () => import('@/components/PIXELUP/Marcas/LogosDinamicos/LogosDinamicos'),
    backComponent: () => import('@/components/PIXELUP/Marcas/LogosDinamicos/LogosDinamicosBO'),
    previewComponent: () => import('@/components/PIXELUP/Marcas/LogosDinamicos/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "testimonios01",
    title: "Testimonios 01",
    description: "Testimonios de la página",
    category: "Social",
    frontComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios01/Testimonios01'),
    backComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios01/Testimonios01BO'),
    previewComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios01/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "testimonios02",
    title: "Testimonios 02",
    description: "Testimonios de la página",
    category: "Social",
    frontComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios02/Testimonios02'),
    backComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios02/Testimonios02BO'),
    previewComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios02/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "testimonios03",
    title: "Testimonios 03",
    description: "Testimonios de la página",
    category: "Social",
    frontComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios03/Testimonios03'),
    backComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios03/Testimonios03BO'),
    previewComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios03/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "testimonios04",
    title: "Testimonios 04",
    description: "Testimonios de la página",
    category: "Social",
    frontComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios04/Testimonios04'),
    backComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios04/Testimonios04BO'),
    previewComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios04/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "testimonios05",
    title: "Testimonios 05",
    description: "Testimonios de la página",
    category: "Social",
    frontComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios05/Testimonios05'),
    backComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios05/Testimonios05BO'),
    previewComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios05/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "testimonios06",
    title: "Testimonios 06",
    description: "Testimonios de la página",
    category: "Social",
    frontComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios06/Testimonios06'),
    backComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios06/Testimonios06BO'),
    previewComponent: () => import('@/components/PIXELUP/Testimonios/Testimonios06/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "feedinstagram",
    title: "Feed Instagram",
    description: "Feed Instagram de la página",
    category: "Social",
    frontComponent: () => import('@/components/PIXELUP/FeedInstagram/FeedInstagram'),
    backComponent: () => import('@/components/PIXELUP/FeedInstagram/FeedInstagramBO'),
    previewComponent: () => import('@/components/PIXELUP/FeedInstagram/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "categoria01",
    title: "Categoría 01",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria01/Categoria01'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria01/CategoriaBO01'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria01/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria02",
    title: "Categoría 02",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria02/Categoria02'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria02/CategoriaBO02'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria02/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria03",
    title: "Categoría 03",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria03/Categoria03'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria03/CategoriaBO03'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria03/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria04",
    title: "Categoría 04",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria04/Categoria04'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria04/CategoriaBO04'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria04/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria05",
    title: "Categoría 05",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria05/Categoria05'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria05/CategoriaBO05'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria05/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria06",
    title: "Categoría 06",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria06/Categoria06'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria06/CategoriaBO06'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria06/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria07",
    title: "Categoría 07",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria07/Categoria07'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria07/CategoriaBO07'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria07/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria08",
    title: "Categoría 08",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria08/Categoria08'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria08/CategoriaBO08'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria08/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria09",
    title: "Categoría 09",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria09/Categoria09'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria09/Categoria09BO'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria09/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "categoria10",
    title: "Categoría 10",
    description: "Categoría de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Categorias/Categoria10/Categoria10'),
    backComponent: () => import('@/components/PIXELUP/Categorias/Categoria10/Categoria10BO'),
    previewComponent: () => import('@/components/PIXELUP/Categorias/Categoria10/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "colecciones01",
    title: "Colecciones 01",
    description: "Colecciones de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Colecciones/Colecciones01/Colecciones01'),
    backComponent: () => import('@/components/PIXELUP/Colecciones/Colecciones01/Colecciones01BO'),
    previewComponent: () => import('@/components/PIXELUP/Colecciones/Colecciones01/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "colecciones02",
    title: "Colecciones 02",
    description: "Colecciones de la página",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Colecciones/Colecciones02/Colecciones02'),
    backComponent: () => import('@/components/PIXELUP/Colecciones/Colecciones02/Colecciones02BO'),
    previewComponent: () => import('@/components/PIXELUP/Colecciones/Colecciones02/Preview'),
    showInHome: true,
    showInAbout: false,
  },
  {
    id: "ubicacion01",
    title: "Ubicación 01",
    description: "Ubicación de la página",
    category: "Ubicación",
    frontComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion'),
    backComponent: () => import('@/components/PIXELUP/Ubicacion/UbicacionBO'),
    previewComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "ubicacion02",
    title: "Ubicación 02",
    description: "Ubicación de la página",
    category: "Ubicación",
    frontComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion02/Ubicacion02'),
    backComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion02/Ubicacion02BO'),
    previewComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion02/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "ubicacion03",
    title: "Ubicación 03",
    description: "Ubicación de la página",
    category: "Ubicación",
    frontComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion03/Ubicacion03'),
    backComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion03/Ubicacion03BO'),
    previewComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion03/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "ubicacion04",
    title: "Ubicación 04",
    description: "Ubicación de la página",
    category: "Ubicación",
    frontComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion04/Ubicacion04'),
    backComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion04/Ubicacion04BO'),
    previewComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion04/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "ubicacion05",
    title: "Ubicación 05",
    description: "Ubicación de la página",
    category: "Ubicación",
    frontComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion05/Ubicacion05'),
    backComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion05/Ubicacion05BO'),
    previewComponent: () => import('@/components/PIXELUP/Ubicacion/Ubicacion05/Preview'),
    showInHome: true,
    showInAbout: true,
  },
  {
    id: "destacadosCat",
    title: "Destacados Cat",
    description: "Destacados de categorías",
    category: "Categorías Colecciones",
    frontComponent: () => import('@/components/PIXELUP/Destacados/Destacado01'),
    backComponent: () => import('@/components/PIXELUP/Destacados/DestacadosCat/DestacadosCatBO'),
    showInHome: true,
    showInAbout: false,
    props: { text: "Destacados" },
  },
  {
    id: "bannerAbout",
    title: "Banner About",
    description: "Banner principal de la página About Us",
    category: "Banners",
    frontComponent: () => import('@/components/PIXELUP/BannerAbout/BannerAbout/BannerAbout'),
    backComponent: () => import('@/components/PIXELUP/BannerAbout/BannerAbout/BannerAboutBO'),
    previewComponent: () => import('@/components/PIXELUP/BannerAbout/BannerAbout/Preview'),
    showInHome: false,
    showInAbout: true,
  },
  {
    id: "aboutUs",
    title: "About Us Texto",
    description: "Contenido principal de la página About Us",
    category: "Contenido",
    frontComponent: () => import('@/components/PIXELUP/About/About01/About01'),
    backComponent: () => import('@/components/PIXELUP/About/About01/BackOffice/About01BO'),
    previewComponent: () => import('@/components/PIXELUP/About/About01/Preview'),
    showInHome: false,
    showInAbout: true,
  },
];

// Funciones de utilidad para filtrar componentes
export const getComponentsForPage = (page: 'home' | 'about') => {
  return availableComponents.filter(component => {
    if (page === 'home') return component.showInHome;
    if (page === 'about') return component.showInAbout;
    return false;
  });
};

export const getFrontComponents = () => {
  return availableComponents.filter(component => component.frontComponent);
};

export const getBackComponents = () => {
  return availableComponents.filter(component => component.backComponent);
}; 





